name: Lines of Code Report

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday
  workflow_dispatch:

jobs:
  count-loc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Calculate Lines of Code
        id: loc
        uses: PavanMudigonda/lines-of-code-reporter@v1.6
        with:
          directory: "."  # Adjust if you want to specify directories
          exclude_dir: "node_modules,.github"  # Exclude unnecessary directories

      - name: Update README with LOC
        run: |
          echo "## 📊 Lines of Code Report" > loc-report.md
          echo "\`\`\`" >> loc-report.md
          echo "${{ steps.loc.outputs.lines-of-code-summary }}" >> loc-report.md
          echo "\`\`\`" >> loc-report.md
          sed -i '/<!-- LOC-START -->/,/<!-- LOC-END -->/c\<!-- LOC-START -->\n'"$(cat loc-report.md)"'\n<!-- LOC-END -->' README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update LOC in README"
          git push
